ALTER TABLE public.clubs 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS key_activities TEXT,
ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS youtube_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS website_url VARCHAR(255);
